### ISSUE TITLE
IPMI Access on SuperMicro - nojava-ipmi-kvm

### ISSUE THREAD

**Issue by mcaselani** [sciapp/nojava-ipmi-kvm#27]
Hello There!

Im trying to use nojava to access and ipmi endpoint, but while accessing the provided url he almost immediately shuts down de novnc screen and shots a button to reconnect. When i try to do that, the process repeat over and over, i can see vnc trying to connect to something before throwing me back to reconnect button.

Providing a full run with --debug would help ?

its seems to be a problem with javaws or x11vnc, but im not so sure.

**Comment by Jeff-liaojinfu** [comment]
您的邮件我已经收到，我会尽快回复您！

**Comment by IngoMeyer441** [comment]
Yes, a run with debug output would be helpful. I guess it is some kind of misconfiguration of API endpoints.

**Comment by mcaselani** [comment]
Hi @IngoMeyer441 , thank you for your reply.

Attached the log file output to this quote.

[nojava-debug-output.txt](https://github.com/user-attachments/files/16087814/nojava-debug-output.txt)

**File .nojava-ipmi-kvmrc.yaml content:**

```
templates:
  ikvm-supermicro:
    skip_login: False
    login_user: <some_user>
    login_endpoint: cgi/login.cgi
    allow_insecure_ssl: true
    user_login_attribute_name: name
    password_login_attribute_name: pwd
    send_post_data_as_json: False
    session_cookie_key: SID
    download_endpoint: cgi/url_redirect.cgi?url_name=ikvm&url_type=jwsk
    java_version: 8u91
    format_jnlp: False
hosts:
  <some_host>:
    based_on: ikvm-supermicro
    full_hostname: <some_host>.fqdn
```
